//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEAmedia.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media_Files
    {
        public int Media_ID { get; set; }
        public string Media_Title { get; set; }
        public string Rel_Path { get; set; }
        public int Uploader_ID { get; set; }
        public System.DateTime Date_Time { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
