//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEAmedia.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Media_Files = new HashSet<Media_Files>();
            this.Messages = new HashSet<Messages>();
            this.Messages1 = new HashSet<Messages>();
            this.Profile_Comments = new HashSet<Profile_Comments>();
            this.Profile_Comments1 = new HashSet<Profile_Comments>();
        }
    
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Email { get; set; }
        public string Password { get; set; }
        public string Password_Salt { get; set; }
    
        public virtual ICollection<Media_Files> Media_Files { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Messages> Messages1 { get; set; }
        public virtual ICollection<Profile_Comments> Profile_Comments { get; set; }
        public virtual ICollection<Profile_Comments> Profile_Comments1 { get; set; }
    }
}
