//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStream
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int entry_id { get; set; }
        public int author_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date_and_time { get; set; }
        public string entry { get; set; }
        public Nullable<int> is_comment_for { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
