//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStream
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid UserID { get; set; }
        public string Username { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
    }
}
