//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStream
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Guestbook = new HashSet<Guestbook>();
            this.Guestbook1 = new HashSet<Guestbook>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string password { get; set; }
        public string password_salt { get; set; }
    
        public virtual ICollection<Guestbook> Guestbook { get; set; }
        public virtual ICollection<Guestbook> Guestbook1 { get; set; }
    }
}
